### ISSUE TITLE
Feedback to implementation

### ISSUE THREAD

**Issue by andrewgreenh** [pabra/react-hooksack#1]
Hello Patrick,

I saw that you are going to present this library at the Dresden.js Meetup today so I had a look at the source code and noticed 2 "problems":

- **Memory leak in concurrent mode**: You are "subscribing" to the store in the render method and cleanup this subscription in the useEffect cleanup. When rendering a component that suspends, the render function will be called, without committing (so no useEffect). When the user unmounts this uncommitted component, the useEffect cleanup will never run, as the effect has never run, thus keeping the callback in the "global" array forever. A simple [reproduction](https://codesandbox.io/s/yjxo4l9pzj) can be seen here: When clicking on a user and then clicking on another user, the console will never "cleanup" for the first user.
The fix for this would be, to only subscribe to the store in the useEffect.

- **Support for state updater functions**: As many users are used to updating the useState state with state updates (`setState(oldState => oldState + 1)`), you could think about supporting that aswell.

**Comment by pabra** [comment]
Hello Andreas,

many thanks for your feedback. :)

1) The memory leak will be fixed.

2) I thought about (later) adding support for a reducer function and returning `dispatch` instead of `setState`. I'll see if/how I get both together.

PS: the Meetup will be tomorrow. ^^
